import { faCar, faTruckPickup, faMountain, faVanShuttle, faBusSimple } from '@fortawesome/free-solid-svg-icons';

const vehiculesData = [
  {
    id: 1,
    type: 'suv',
    name: 'Nissan PATROL',
    image: '/images/nissan_patrol.jpg',
    price: 23000,
    engine: 'V6',
    power: '400 ch',
    fuel: 'Essence',
    transmission: 'Automatique, 7 vitesses',
    traction: '4x4',
    doors: 5,
    seats: 7,
    year: 2023,
    version: 'Tekna',
    exteriorColor: 'Gris',
    interiorColor: 'Beige',
    cylinders: 6,
    displacement: '5.552 cm³',
    emissionStandard: 'Euro 6',
    wheelbase: '3.13 m',
  },
  {
    id: 2,
    type: 'suv',
    name: 'Another SUV Model',
    image: '/images/another_suv.jpg', // Replace with actual image path
    price: 28000,
    engine: 'L4 Turbo',
    power: '250 ch',
    fuel: 'Essence',
    transmission: 'Automatique, 8 vitesses',
    traction: '4x4',
    doors: 5,
    seats: 5,
    year: 2024,
    version: 'Limited',
    exteriorColor: 'Bleu',
    interiorColor: 'Noir',
    cylinders: 4,
    displacement: '2.0 L',
    emissionStandard: 'Euro 7',
    wheelbase: '2.90 m',
  },
  {
    id: 3,
    type: 'pickup',
    name: 'Ford Ranger',
    image: '/images/ford_ranger.jpg', // Replace with actual image path
    price: 35000,
    engine: '2.0L Bi-Turbo Diesel',
    power: '213 ch',
    fuel: 'Diesel',
    transmission: 'Automatique, 10 vitesses',
    traction: '4x4',
    doors: 4,
    seats: 5,
    year: 2023,
    version: 'Wildtrak',
    exteriorColor: 'Orange',
    interiorColor: 'Gris Foncé',
    cylinders: 4,
    displacement: '1996 cm³',
    emissionStandard: 'Euro 6d',
    wheelbase: '3.27 m',
  },
  {
    id: 4,
    type: '4x4',
    name: 'Jeep Wrangler',
    image: '/images/jeep_wrangler.jpg', // Replace with actual image path
    price: 42000,
    engine: '3.6L V6',
    power: '285 ch',
    fuel: 'Essence',
    transmission: 'Manuelle, 6 vitesses',
    traction: '4x4',
    doors: 4,
    seats: 5,
    year: 2024,
    version: 'Rubicon',
    exteriorColor: 'Vert',
    interiorColor: 'Noir',
    cylinders: 6,
    displacement: '3604 cm³',
    emissionStandard: 'Euro 7',
    wheelbase: '3.01 m',
  },
  {
    id: 5,
    type: 'suv',
    name: 'Toyota RAV4',
    image: '/images/toyota_rav4.jpg', // Replace with actual image path
    price: 32000,
    engine: '2.5L Hybride',
    power: '222 ch',
    fuel: 'Hybride Essence/Electrique',
    transmission: 'Automatique',
    traction: 'AWD',
    doors: 5,
    seats: 5,
    year: 2023,
    version: 'Dynamic Force',
    exteriorColor: 'Blanc',
    interiorColor: 'Noir',
  },
  {
    id: 6,
    type: 'suv',
    name: 'Hyundai Tucson',
    image: '/images/hyundai_tucson.jpg', // Replace with actual image path
    price: 29000,
    engine: '1.6L Turbo Hybrid',
    power: '230 ch',
    fuel: 'Hybride Essence/Electrique',
    transmission: 'Automatique, 7 vitesses',
    traction: '2WD',
    doors: 5,
    seats: 5,
    year: 2024,
    version: 'Executive',
    exteriorColor: 'Gris',
    interiorColor: 'Gris',
  },
  {
    id: 7,
    type: 'suv',
    name: 'Kia Sportage',
    image: '/images/kia_sportage.jpg', // Replace with actual image path
    price: 27500,
    engine: '1.6L CRDi',
    power: '136 ch',
    fuel: 'Diesel',
    transmission: 'Manuelle, 6 vitesses',
    traction: '2WD',
    doors: 5,
    seats: 5,
    year: 2023,
    version: 'Active',
    exteriorColor: 'Rouge',
    interiorColor: 'Noir',
  },
  {
    id: 8,
    type: 'suv',
    name: 'Peugeot 3008',
    image: '/images/peugeot_3008.jpg', // Replace with actual image path
    price: 31000,
    engine: '1.2L PureTech',
    power: '130 ch',
    fuel: 'Essence',
    transmission: 'Automatique, 8 vitesses',
    traction: '2WD',
    doors: 5,
    seats: 5,
    year: 2024,
    version: 'Allure',
    exteriorColor: 'Blanc Nacré',
    interiorColor: 'Noir',
  },
  {
    id: 9,
    type: 'suv',
    name: 'Renault Kadjar',
    image: '/images/renault_kadjar.jpg', // Replace with actual image path
    price: 26000,
    engine: '1.3L TCe',
    power: '140 ch',
    fuel: 'Essence',
    transmission: 'Manuelle, 6 vitesses',
    traction: '2WD',
    doors: 5,
    seats: 5,
    year: 2023,
    version: 'Zen',
    exteriorColor: 'Gris Platine',
    interiorColor: 'Gris Foncé',
  },
  {
    id: 10,
    type: 'suv',
    name: 'Citroën C5 Aircross',
    image: '/images/citroen_c5_aircross.jpg', // Replace with actual image path
    price: 28500,
    engine: '1.5L BlueHDi',
    power: '130 ch',
    fuel: 'Diesel',
    transmission: 'Automatique, 8 vitesses',
    traction: '2WD',
    doors: 5,
    seats: 5,
    year: 2024,
    version: 'Shine',
    exteriorColor: 'Bleu Eclipse',
    interiorColor: 'Gris',
  },
  {
    id: 11,
    type: '4x4',
    name: 'Land Rover Defender',
    image: '/images/land_rover_defender.jpg', // Replace with actual image path
    price: 55000,
    engine: '2.0L P300',
    power: '300 ch',
    fuel: 'Essence',
    transmission: 'Automatique, 8 vitesses',
    traction: 'AWD',
    doors: 5,
    seats: 5,
    year: 2023,
    version: 'SE',
    exteriorColor: 'Vert Gondwana',
    interiorColor: 'Noir',
  },
  {
    id: 12,
    type: '4x4',
    name: 'Mercedes-Benz Classe G',
    image: '/images/mercedes_g_class.jpg', // Replace with actual image path
    price: 120000,
    engine: '4.0L V8 Biturbo',
    power: '422 ch',
    fuel: 'Essence',
    transmission: 'Automatique, 9 vitesses',
    traction: 'AWD',
    doors: 5,
    seats: 5,
    year: 2024,
    version: 'G 500',
    exteriorColor: 'Noir Obsidienne',
    interiorColor: 'Cuir Nappa Noir',
  },
  {
    id: 13,
    type: '4x4',
    name: 'BMW X5',
    image: '/images/bmw_x5.jpg', // Replace with actual image path
    price: 68000,
    engine: '3.0L xDrive40i',
    power: '340 ch',
    fuel: 'Essence',
    transmission: 'Automatique, 8 vitesses',
    traction: 'AWD',
    doors: 5,
    seats: 5,
    year: 2023,
    version: 'xLine',
    exteriorColor: 'Blanc Alpin',
    interiorColor: 'Cuir Vernasca Noir',
  },
  {
    id: 14,
    type: '4x4',
    name: 'Audi Q7',
    image: '/images/audi_q7.jpg', // Replace with actual image path
    price: 70000,
    engine: '3.0L TDI quattro',
    power: '286 ch',
    fuel: 'Diesel',
    transmission: 'Automatique, 8 vitesses',
    traction: 'AWD',
    doors: 5,
    seats: 7,
    year: 2024,
    version: 'S line',
    exteriorColor: 'Gris Daytona',
    interiorColor: 'Alcantara/Cuir Noir',
  },
  {
    id: 15,
    type: 'pickup',
    name: 'Toyota Hilux',
    image: '/images/toyota_hilux.jpg', // Replace with actual image path
    price: 30000,
    engine: '2.4L D-4D',
    power: '150 ch',
    fuel: 'Diesel',
    transmission: 'Manuelle, 6 vitesses',
    traction: '4x4',
    doors: 4,
    seats: 5,
    year: 2023,
    version: 'Legend',
    exteriorColor: 'Gris Atlas',
    interiorColor: 'Tissu Gris Foncé',
  },
  {
    id: 16,
    type: 'pickup',
    name: 'Nissan Navara',
    image: '/images/nissan_navara.jpg', // Replace with actual image path
    price: 28000,
    engine: '2.3L dCi',
    power: '163 ch',
    fuel: 'Diesel',
    transmission: 'Manuelle, 6 vitesses',
    traction: '4x4',
    doors: 4,
    seats: 5,
    year: 2024,
    version: 'Tekna',
    exteriorColor: 'Blanc Lunaire',
    interiorColor: 'Cuir Noir',
  },
  {
    id: 17,
    type: 'pickup',
    name: 'Mitsubishi L200',
    image: '/images/mitsubishi_l200.jpg', // Replace with actual image path
    price: 27000,
    engine: '2.2L DI-D',
    power: '150 ch',
    fuel: 'Diesel',
    transmission: 'Manuelle, 6 vitesses',
    traction: '4x4',
    doors: 4,
    seats: 5,
    year: 2023,
    version: 'Invite+',
    exteriorColor: 'Blanc',
    interiorColor: 'Tissu Noir',
  },
  {
    id: 18,
    type: 'pickup',
    name: 'Volkswagen Amarok',
    image: '/images/volkswagen_amarok.jpg', // Replace with actual image path
    price: 38000,
    engine: '3.0L V6 TDI',
    power: '204 ch',
    fuel: 'Diesel',
    transmission: 'Automatique, 8 vitesses',
    traction: '4Motion',
    doors: 4,
    seats: 5,
    year: 2024,
    version: 'Highline',
    exteriorColor: 'Bleu Ravenna',
    interiorColor: 'Cuir Noir',
  },
  {
    id: 19,
    type: 'suv',
    name: 'Dacia Duster',
    image: '/images/dacia_duster.jpg', // Replace with actual image path
    price: 18000,
    engine: '1.5L dCi',
    power: '115 ch',
    fuel: 'Diesel',
    transmission: 'Manuelle, 6 vitesses',
    traction: '4x2',
    doors: 5,
    seats: 5,
    year: 2023,
    version: 'Prestige',
    exteriorColor: 'Orange Atacama',
    interiorColor: 'Tissu Noir',
  },
  {
    id: 20,
    type: 'suv',
    name: 'Skoda Karoq',
    image: '/images/skoda_karoq.jpg', // Replace with actual image path
    price: 25000,
    engine: '1.5L TSI',
    power: '150 ch',
    fuel: 'Essence',
    transmission: 'Manuelle, 6 vitesses',
    traction: '4x2',
    doors: 5,
    seats: 5,
    year: 2024,
    version: 'Style',
    exteriorColor: 'Gris Business',
    interiorColor: 'Tissu Noir',
  },
];

export const vehiculeTypeIcons = {
  suv: faCar,
  pickup: faTruckPickup,
  '4x4': faMountain,
  minibus:faBusSimple,
  van:faVanShuttle,
};

export default vehiculesData;